In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0-rc1


In [2]:
print(tf.test.is_gpu_available())

True


# 张量

In [3]:
# Rank 0
mammal=tf.Variable("Elephant",tf.string)
tf.print(tf.rank(mammal))
tf.print(tf.shape(mammal))


0
[]


In [4]:
print(tf.rank(mammal))

tf.Tensor(0, shape=(), dtype=int32)


In [5]:
#Rank 1
mystr=tf.Variable(["Hello"],tf.string)
tf.print(tf.rank(mystr))
tf.print(tf.shape(mystr))


1
[1]


In [6]:
#Rank 2
mymat=tf.Variable([[7],[11]],tf.int16)
tf.print(tf.rank(mymat))
tf.print(tf.shape(mymat))


2
[2 1]


创建张量

In [7]:
tf.constant([1,2,3],dtype=tf.int16)

<tf.Tensor: id=42, shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

In [8]:
tf.zeros((2,2),dtype=tf.int16)

<tf.Tensor: id=45, shape=(2, 2), dtype=int16, numpy=
array([[0, 0],
       [0, 0]], dtype=int16)>

In [17]:
#reshape
rank_three_tensor=tf.ones([3,4,5])
matrix=tf.reshape(rank_three_tensor,[6,10])

In [ ]:
yet_another=tf.reshape(rank_three_tensor,[8, 10])#报错

# 操作

- tf.strings
- tf.debugging
- tf.dtypes
- tf.math
- tf.random
- tf.feature_column  [建议参考](https://www.tensorflow.org/tutorials/structured_data/feature_columns)，常用于特征处理.


## tf.strings

In [9]:
#字符切割
tf.strings.bytes_split('hello')

<tf.Tensor: id=104, shape=(5,), dtype=string, numpy=array([b'h', b'e', b'l', b'l', b'o'], dtype=object)>

In [ ]:
help(tf.strings.split)

In [20]:
#单词切割
tf.strings.split('hello world')

<tf.Tensor: id=699, shape=(2,), dtype=string, numpy=array([b'hello', b'world'], dtype=object)>

In [22]:
#string hash
tf.strings.to_hash_bucket(['hello','world'], num_buckets=10)

<tf.Tensor: id=701, shape=(2,), dtype=int64, numpy=array([8, 1], dtype=int64)>

## tf.debugging

In [23]:
#tf自带debug函数
a=tf.random.uniform((10,10))
tf.debugging.assert_equal(x=a.shape,y=(10,10))


In [ ]:
#错误示范
tf.debugging.assert_equal(x=a.shape,y=(20,10))

## tf.random


In [25]:
a = tf.random.uniform(shape=(10,5),minval=0,maxval=10)
a

<tf.Tensor: id=781, shape=(10, 5), dtype=float32, numpy=
array([[7.337245  , 8.563206  , 0.12907624, 7.0185113 , 6.942792  ],
       [8.801897  , 0.03558278, 0.71659565, 9.032879  , 2.803135  ],
       [6.875329  , 5.959874  , 4.161513  , 8.744188  , 3.4625864 ],
       [0.5550134 , 6.3781047 , 5.8278823 , 2.9698002 , 0.16484618],
       [7.8418264 , 9.058552  , 1.5147066 , 0.60814023, 5.9776535 ],
       [8.623667  , 5.124526  , 7.912209  , 7.0718718 , 7.3142266 ],
       [8.501612  , 1.7961097 , 6.5727043 , 0.8518863 , 6.5302753 ],
       [9.651488  , 1.1181915 , 7.478503  , 4.9840236 , 5.1185536 ],
       [4.7294226 , 3.1436408 , 9.654947  , 5.030531  , 3.061322  ],
       [7.6798067 , 1.7466497 , 4.6031084 , 5.355513  , 8.813373  ]],
      dtype=float32)>

## tf.math

In [27]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])

tf.print(tf.math.add(a,b))
tf.print(tf.math.subtract(a,b))
tf.print(tf.math.multiply(a,b))
tf.print(tf.math.divide(a,b))

[[6 8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[5 12]
 [21 32]]
[[0.2 0.33333333333333331]
 [0.42857142857142855 0.5]]


In [28]:
print(tf.math.add(a,b))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


## tf.dtypes

In [29]:
x =tf.constant([1.8,2.2],dtype=tf.float32)

x1=tf.dtypes.cast(x,tf.int32)
x1

<tf.Tensor: id=796, shape=(2,), dtype=int32, numpy=array([1, 2])>

# 常用层

- tf.keras.layers
- tf.nn

在大多数据情况下，可以使用TensorFlow封装的tf.keras.layers构建的一些层建模，Keras层是非常有用的。

可以在[文档中](https://www.tensorflow.org/api_docs/python/tf/keras/layers)查看预先存在的层的完整列表。它包括Dense，Conv2D，LSTM，BatchNormalization，Dropout等。

In [39]:
#文本分类

a = tf.random.uniform(shape = (10,100,50),minval=-0.5,maxval=0.5) #张量

x = tf.keras.layers.LSTM(100)(a) #LSTM

x = tf.keras.layers.Dense(10)(x) #全连接层

x = tf.nn.softmax(x) #激活函数



增加层的参数配置

In [41]:
#层中增加激活函数
tf.keras.layers.Dense(64, activation='relu')
#or
tf.keras.layers.Dense(64, activation=tf.nn.relu)


#将L1正则化系数为0.01的线性层应用于内核矩阵
tf.keras.layers.Dense(64, kernel_regularizer=tf.keras.regularizers.l1(0.01))

# 将L2正则化系数为0.01的线性层应用于偏差向量：
tf.keras.layers.Dense(64, bias_regularizer=tf.keras.regularizers.l2(0.01))

# 内核初始化为随机正交矩阵的线性层：
tf.keras.layers.Dense(64, kernel_initializer='orthogonal')

# 偏差向量初始化为2.0的线性层：
tf.keras.layers.Dense(64, bias_initializer=tf.keras.initializers.Constant(2.0))