In [2]:
import tensorflow_hub as hub

embed = hub.load("./nnlm-zh-dim50-with-normalization_2")


In [26]:
embeddings = embed(["男 人", "女 人"])
embeddings.shape

TensorShape([2, 50])

In [27]:
embeddings[0]

<tf.Tensor: id=461, shape=(50,), dtype=float32, numpy=
array([-0.0723118 , -0.02261443, -0.13093795, -0.10121617,  0.24167016,
       -0.1516153 , -0.21132687, -0.03447215,  0.41586655, -0.06008016,
        0.07898698,  0.14647418, -0.13860698,  0.02432544,  0.01865583,
       -0.10847726, -0.10081095,  0.24029845, -0.20584469,  0.26454794,
        0.02923219, -0.09868159,  0.13764317, -0.00866372, -0.31003717,
        0.21122254, -0.22883596,  0.21857198, -0.13977836, -0.18633413,
       -0.13354269,  0.03527712, -0.00228143,  0.05794042,  0.21858081,
       -0.15768361,  0.03689402, -0.3237845 ,  0.06260592,  0.01628113,
       -0.34706676,  0.15438409, -0.06346516, -0.12056275,  0.03185892,
       -0.26768813, -0.13757196, -0.12488624,  0.01995356,  0.05919786],
      dtype=float32)>

In [28]:
embeddings[1]

<tf.Tensor: id=465, shape=(50,), dtype=float32, numpy=
array([-0.07964583,  0.00043416, -0.1464676 , -0.08468687,  0.18957299,
       -0.11347295, -0.21707432, -0.06135448,  0.42221537, -0.07161589,
        0.12347831,  0.11899923, -0.1860566 ,  0.05610096,  0.02894448,
       -0.07197039, -0.12848333,  0.22532476, -0.19169675,  0.29881644,
        0.00897528, -0.12392566,  0.13083367, -0.01802753, -0.31276983,
        0.20541279, -0.2002562 ,  0.19910054, -0.10586128, -0.14971647,
       -0.12818956,  0.0317865 ,  0.02450224,  0.04940631,  0.26318878,
       -0.17156339,  0.07450796, -0.2970022 ,  0.0302104 ,  0.03484252,
       -0.3919885 ,  0.10235768, -0.08340716, -0.07391408,  0.05020208,
       -0.27667862, -0.15101378, -0.11863364,  0.00094551,  0.05136123],
      dtype=float32)>

In [29]:
v1 = embeddings[0].numpy().reshape(1,-1)
v2 = embeddings[1].numpy().reshape(1,-1)

In [30]:
import sklearn
sklearn.metrics.pairwise.cosine_similarity(v1, v2)

array([[0.98703706]], dtype=float32)

In [33]:
import tensorflow as tf

In [34]:
hub_layer = hub.KerasLayer("./nnlm-zh-dim50-with-normalization_2", output_shape=[50],
                           input_shape=[], dtype=tf.string)

model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 50)                48558850  
_________________________________________________________________
dense (Dense)                (None, 16)                816       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 48,559,683
Trainable params: 833
Non-trainable params: 48,558,850
_________________________________________________________________
